name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

      - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-artifact
        path: path/to/artifacts
